name: Inspect

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init
        uses: ./.github/actions/init

      - name: Build
        run: pnpm build

      - name: Prepare gh-pages artifact
        run: |
          mkdir -p _site
          cp -r example.html dist _site

      - name: Upload gh-pages build
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy-pages:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/release' }}

    needs: build

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: deploy-pages
      cancel-in-progress: true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
